### ISSUE TITLE
how to print sharding plan

### ISSUE THREAD

**Issue by xiexbing** [pytorch/torchrec#1554]
Hello, I want  to write a standalone sharding planner based on the tutorial. I can use print(model.plan) to get the detailed plan but not the sharding plan log as the tutorial showed. Should I use pytorch log or some other profiling logs to print it?

**Comment by bigning** [comment]
Hi as long as here the debug=True https://fburl.com/8spjktn4, it should print the plan. It uses the logging class https://fburl.com/jvxnmnsq, maybe you could also check the stderr, not only the stdout

**Comment by henrylhtsang** [comment]
you can also use `print(planner.stats[0]._stats_table)`, after calling planner.plan

**Comment by xiexbing** [comment]
thanks for your responses.

I tried both of the your suggestions.
1. for the debug and and logging options. I added debug=True and tried to
print stderr to stdout, and I didn't get the printed sharding placement in
log. BTW, the links you referred cannot be accessed externally.

2. I tried to add the planner stat printout to my code and got an error
like:
 print(planner.stats[0]._stats_table)
AttributeError: 'EmbeddingShardingPlanner' object has no attribute 'stats'
    print(planner.stats[0]._stats_table)
AttributeError: 'EmbeddingShardingPlanner' object has no attribute 'stats'
    print(planner.stats[0]._stats_table)
AttributeError: 'EmbeddingShardingPlanner' object has no attribute 'stats'

my code clip is:
from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
.......
 planner = EmbeddingShardingPlanner(
            topology=Topology(...),
            ...
            debug=True,
        )
...
plan = planner.collective_plan(tables, sharders, pg)
print(planner.stats[0]._stats_table)

**Comment by henrylhtsang** [comment]
@xiexbing my bad, can you change `planner.stats` to `planner._stats`?

Also try printing it like 
```
for row in self._stats_table:
            logger.info(row)
```

**Comment by xiexbing** [comment]
Yes, the detailed row-based printout works! thanks!
BTW, can I ask another question? in the planning part, I set a large
batch_size = 32K, but from the log printout, in the planning, the batch
size used is still 512. Why?

**Comment by henrylhtsang** [comment]
@xiexbing how did you pass in the batch size? 512 is the default batch size, so I suspect you didn't pass in correctly?

**Comment by xiexbing** [comment]
Here is the printout of my constraints configuration.
{'t_1': ParameterConstraints(sharding_types=['table_wise'],
compute_kernels=None, min_partition=None, pooling_factors=[2],
num_poolings=None, batch_sizes=[32768], is_weighted=False)}. As you can see
that I set the batch_sizes (32K) as part of the parameter constraints.

here is the planner printout on batch size:
[image: image.png]

**Comment by henrylhtsang** [comment]
@xiexbing I can't quite see the picture, but you also need to pass in batch_size when you init the planner.

**Comment by xiexbing** [comment]
this is my code on building planner:
     planner = EmbeddingShardingPlanner(
            topology=Topology(
                ...
            ),
            constraints=constraints_configs,
        )
the constraints_configs is my previous printout, including the batch size
set as 32768.
Is there anywhere else I need to set the batch size constraints? the figure
I shared is the planner printout with batch size as 512 (the default).

**Comment by henrylhtsang** [comment]
@xiexbing 

second argument of planner. 

```
class EmbeddingShardingPlanner(ShardingPlanner):
    """
    Provides an optimized sharding plan for a given module with shardable parameters
    according to the provided sharders, topology, and constraints.
    """

    def __init__(
        self,
        topology: Optional[Topology] = None,
        batch_size: Optional[int] = None,
        enumerator: Optional[Enumerator] = None,
        storage_reservation: Optional[StorageReservation] = None,
        proposer: Optional[Union[Proposer, List[Proposer]]] = None,
        partitioner: Optional[Partitioner] = None,
        performance_model: Optional[PerfModel] = None,
        stats: Optional[Union[Stats, List[Stats]]] = None,
        constraints: Optional[Dict[str, ParameterConstraints]] = None,
        debug: bool = True,
    ) -> None:
```

**Comment by xiexbing** [comment]
uh. I see. now it works. thanks!
